### ISSUE TITLE
Gulp file not loaded

### ISSUE THREAD

**Issue by ghost** [mithunvp/ng2Mvc5Demo#4]
GulpFile.js doesn't offer the any options in Task Runner, it just says it failed to load -- the output window gives the below error:

Failed to run "[ProjectDirectory]\ng2Mvc5Demo-master\ng2Mvc5Demo\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
[ProjectDirectory]\ng2Mvc5Demo-master\ng2Mvc5Demo\gulpfile.js:13
gulp.task("scriptsNStyles", () => {
                             ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments ([ProjectDirectory]\ng2Mvc5Demo-master\ng2Mvc5Demo\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> ([ProjectDirectory]\ng2Mvc5Demo-master\ng2Mvc5Demo\node_modules\liftoff\index.js:198:16)
    at module.exports ([ProjectDirectory]\ng2Mvc5Demo-master\ng2Mvc5Demo\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> ([ProjectDirectory]\ng2Mvc5Demo-master\ng2Mvc5Demo\node_modules\liftoff\index.js:190:9)

I can't for the life of me see what's wrong with the code in it; it looks fine and is unchanged from the original. Any thoughts?

**Comment by ghost** [comment]
You have TypeScript and Js intermixed in your Gulp file.

In GulpFile.js "gulp.task("scriptsNStyles", () = > " should be "gulp.task("scriptsNStyles", function() "

The options appear for me and the project builds and runs properly now.

**Comment by markau** [comment]
Nice one @kiebor

**Comment by mithunvp** [comment]
Thanks !! It was great catch !!
